### PR TITLE
feat(all): add iterator support to Array.from

### PR DESCRIPTION
**Pull request by AdamWillden**
As per #5

### CODE REVIEW

**Comment by AdamWillden** [comment]
Would you like me to push the commit which contains the build?

**Comment by AdamWillden** [comment]
Finally to clarify.

The changes have been tested using my local application which uses `[...someMap.keys()]`. I have not tested any other configuration however the code should work for any iterable.

I've added a `[Symbol.iterator]` to the object returned by `sharedIterator`. All it does is return itself as the iterator for itself. It follows the design from a snippet of code as follows (located [here](https://hacks.mozilla.org/2015/04/es6-in-depth-iterators-and-the-for-of-loop/)):

>## Iterator objects
> 
> Now, there is a chance you will never have to implement an iterator object of your own from scratch. We’ll see why next week. But for completeness, let’s look at what an iterator object looks like. (If you skip this whole section, you’ll mainly be missing crunchy technical details.)
> 
> A for–of loop starts by calling the [Symbol.iterator]() method on the collection. This returns a new iterator object. An iterator object can be any object with a .next() method; the for–of loop will call this method repeatedly, once each time through the loop. For example, here’s the simplest iterator object I can think of:
> ```js
var zeroesForeverIterator = {
  [Symbol.iterator]: function () {
    return this;
  },
  next: function () {
    return {done: false, value: 0};
  }
};
```

**Comment by AdamWillden** [comment]
Based on your comment in the other PR regarding testing strategy and different browsers: I tested this in IE11, Chrome Version 49.0.2623.87 m (64-bit), Firefox 45.0

**Comment by EisenbergEffect** [comment]
Sounds good. I'll take a look soon.

**Comment by EisenbergEffect** [comment]
Thanks!

**Comment by EisenbergEffect** [comment]
**Thank you for contributing this pull request!** I was about to merge it but then noticed you had not signed the CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

**Comment by AdamWillden** [comment]
@EisenbergEffect  PING :-)

**Comment by AdamWillden** [comment]
I had already read contrib just hadn't signed CLA

**Comment by EisenbergEffect** [comment]
Thanks! I noticed you had formatted the message correct so I was surprise the CLA hadn't been signed. Thanks for your prompt reply. Merging momentarily...

**Pull request merged**
