### PR TITLE
Add Iterator support to Array.from

### PR DESCRIPTION
**Pull request by jods4**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Nice. I'll take a look shortly and we can get a patch release out.

**Comment by EisenbergEffect** [comment]
@jods4 Sorry to bug you and I didn't mean to close issue #4. I just pushed fixes to include a Symbol polyfill as well as iterator support for all collections. I thought that might affect your fix to Array.from. Can you just let me know if you want to change anything or if this PR should remain as is? Thanks for your work on this!

**Comment by EisenbergEffect** [comment]
@jods4 I'm wondering if you would mind rebasing and testing out the changes here?

**Comment by AdamWillden** [comment]
@EisenbergEffect am I correct that there are no unit tests in this project? If so, by 'testing out the changes here' do you mean to try them out in a live application? If so and if @jods4 is not available at the moment I'd be happy to do that task. I can rebase and test his changes, then if all is well I can create a new PR (with credit to jods4).

**Comment by jods4** [comment]
@AdamWillden No need for credits. 
I don't really have the time right now, so feel free to do so.

**Comment by AdamWillden** [comment]
@EisenbergEffect what is the deal with linting this repo. I was going to check I hadn't introduced any lint errors but there are loads.

I think I've got it. Had an issue were Array.from checks for an iterable which is determined by the presence of a `[Symbol.iterator]` property. However the collection `sharedIterator` only specifies a `next` property, as such I've added the required property so it can be considered an iterable:

```javascript
function sharedIterator(itp, array, array2) {
    var p = [0], done = false;
    itp.push(p);
    return {
      [Symbol.iterator]: function () {
        return this;
      },
      next: function() {
        var v, k = p[0];
        if (!done && k < array.length) {
          v = array2 ? [array[k], array2[k]]: array[k];
          p[0]++;
        } else {
          done = true;
          itp.splice(itp.indexOf(p), 1);
        }
        return { done: done, value: v };
      }
    };
  }
```

Should I include the generated `gulp build` files in with the PR

**Comment by AdamWillden** [comment]
I also had another issue where Array.from is implemented in the browser but does not cover iterables

I had to modify the code like this:

```js
var iterable = {
  [Symbol.iterator]: function () {
    var v = 1;
    return { 
      next: function() {
        return { done: !v, value: v-- };
      }
    };
  }
};

if (!Array.from || Array.from && Array.from(iterable).length === 0) {
 ... etc
}
```

Is that acceptable?

**Comment by EisenbergEffect** [comment]
Yes, unfortunately. We need to come up with a test strategy that we can automate a bit more easily with this since any tests here would be only applicable in certain versions of certain browsers.

**Comment by EisenbergEffect** [comment]
* We turned linting off on this library since many of the polyfills are based on other sources and we wanted to keep them as close to their original versions as possible for now.
* Please do not include generated files in the PR.

Thanks!

**Comment by EisenbergEffect** [comment]
Closing this out since we've got a new PR.

**Pull request closed without merging**
