### PR TITLE
fix(symbol): treat `null` value the same as `undefined`

### LINKED ISSUE #13: Uncaught TypeError: Cannot read property 'Symbol(toStringTag)' of null
When loading babel-core@5.8.35/browser.js it will throw this exception [here](https://github.com/aurelia/polyfills/blob/master/src/symbol.js#L251) since it's being called with `null`

For development I configured

```javascript
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ],
    "sourceMaps": "inline"
  },
```
and get this error

### PR DESCRIPTION
**Pull request by stoffeastrom**
Fixes #13

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@stoffeastrom I could have swore that you had submitted PRs before...but I can't find you in our list of CLA signatories. Can you sign the CLA for me? https://docs.google.com/a/durandal.io/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by stoffeastrom** [comment]
Yeah me to but it should be signed!

**Comment by EisenbergEffect** [comment]
Thanks!

**Comment by EisenbergEffect** [comment]
Ok, releasing in the next couple of minutes.

**Pull request merged**
